### ISSUE TITLE
Invalid redirect_uri in request when using SSL

### ISSUE THREAD

**Issue by joshleblanc** [Lichthagel/meteor-accounts-discord#5]
Kind of a weird problem.

Using this service works fine when using http://

However, switching the protocol to https:// causes the following error:

```
App 5659 output: Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with Discord. failed [400] {"error": "invalid_request", "error_description": "Invalid \"redirect_uri\" in request."}
App 5659 output:     at getTokens (packages/lichthagel:discord-oauth/discord_server.js:72:13)
App 5659 output:     at Object.OAuth.registerService.query [as handleOauthRequest] (packages/lichthagel:discord-oauth/discord_server.js:9:20)
App 5659 output:     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
App 5659 output:     at middleware (packages/oauth/oauth_server.js:161:5)
App 5659 output:     at /home/cereal/aa2gd-meteor/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
App 5659 output:   message: 'Failed to complete OAuth handshake with Discord. failed [400] {"error": "invalid_request", "error_description": "Invalid \\"redirect_uri\\" in request."}',
App 5659 output:   response:
App 5659 output:    { statusCode: 400,
App 5659 output:      content: '{"error": "invalid_request", "error_description": "Invalid \\"redirect_uri\\" in request."}',
App 5659 output:      headers:
App 5659 output:       { date: 'Wed, 24 Jul 2019 15:34:02 GMT',
App 5659 output:         'content-type': 'application/json',
App 5659 output:         'content-length': '89',
App 5659 output:         connection: 'close',
App 5659 output:         'set-cookie': [Array],
App 5659 output:         'cache-control': 'no-store',
App 5659 output:         pragma: 'no-cache',
App 5659 output:         'strict-transport-security': 'max-age=31536000; includeSubDomains',
App 5659 output:         via: '1.1 google',
App 5659 output:         'alt-svc': 'clear',
App 5659 output:         'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
App 5659 output:         server: 'cloudflare',
App 5659 output:         'cf-ray': '4fb6f4bc0e2482d7-ATL' },
App 5659 output:      data:
App 5659 output:       { error: 'invalid_request',
App 5659 output:         error_description: 'Invalid "redirect_uri" in request.' } } }
```

I have confirmed the redirect uri is set up correctly in the discord dev portal, I've compared `Meteor.absoluteUrl("_oauth/discord")` to the value shown in the discord login dialog, and they both match.

I don't see any reason why this would be happening, honestly. 

You can see the difference by going to http://famtime.grep.sh and logging in. If you go to https://famtime.grep.sh and try to login, you'll notice it fails in the console. The error I posted above is what's shown on the server.

I can only assume the redirect_uri provided in the token request doesn't match the redirect_uri provided in the original login.

**Comment by joshleblanc** [comment]
This was not a problem with the library.
